add ci

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -47,9 +47,9 @@ jobs:
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data     
           sleep 5
-          
-      - name: Build linux target
-        run: make juicefs
+
+      - name: Build 
+        uses: ./.github/actions/build
 
       - name: Download tool
         run: | 
@@ -58,6 +58,9 @@ jobs:
           
       - name: Test
         run: |
+          # # Consider command as failed when any component of the pipe fails:
+          # https://stackoverflow.com/questions/1221833/pipe-output-and-capture-exit-status-in-bash
+          set -o pipefail
           meta_url=redis://127.0.0.1/1
           mount_point=/tmp/sync-test/
           ./mc config host add minio http://127.0.0.1:9000 minioadmin minioadmin
@@ -86,8 +89,4 @@ jobs:
         uses: juicedata/slack-notify-action@main
         with:
           channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
-          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  
-
-      - name: Setup upterm session
-        if: ${{ failure() }}
-        uses: lhotari/action-upterm@v1
+          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"
diff --git a/.github/workflows/pjdfstest.yml b/.github/workflows/pjdfstest.yml
--- a/.github/workflows/pjdfstest.yml
+++ b/.github/workflows/pjdfstest.yml
@@ -16,20 +16,48 @@ on:
     paths-ignore:
       - 'docs/**'
       - '**.md'
+      - '.github/**'
+  schedule:
+    - cron:  '0 16 * * *'
   workflow_dispatch:
 
 jobs:
-  pjdfstest:
+  build-matrix:
     runs-on: ubuntu-latest
     steps:
-      - name: Set up Go
-        uses: actions/setup-go@v2
-        with:
-          go-version: '1.17.x'
+      - id: set-matrix
+        run: |
+          echo "github.event_name is ${{github.event_name}}"
+          echo "GITHUB_REF_NAME is ${GITHUB_REF_NAME}"
+          if [ "${{github.event_name}}" == "schedule"  ]; then
+            echo '::set-output name=meta_matrix::["sqlite3", "redis", "mysql", "tikv", "tidb", "postgres", "badger", "mariadb", "fdb"]'
+          else
+            echo '::set-output name=meta_matrix::["redis"]'
+          fi
+    outputs:
+      meta_matrix: ${{ steps.set-matrix.outputs.meta_matrix }}
 
-      - name: Set up Docker
-        uses: docker-practice/actions-setup-docker@master
-
+  pjdfstest:
+    needs: build-matrix
+    strategy:
+      fail-fast: false
+      matrix:
+        # [ 'sqlite3', 'redis', 'mysql', 'tikv', 'tidb', 'postgres', 'badger', 'mariadb', 'fdb']
+        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
+    runs-on: ubuntu-latest
+    services:
+      postgres:
+        image: postgres
+        env:
+          POSTGRES_PASSWORD: postgres
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+        ports:
+          - 5432:5432
+    steps:
       - uses: shogo82148/actions-setup-perl@v1
         with:
           perl-version: '5.34'
@@ -39,21 +67,46 @@ jobs:
         with:
           fetch-depth: 1
 
-      - name: Build linux target
-        run: make juicefs
-
-      - name: Run Redis
+      - name: Set Variable
+        id: vars
         run: |
-          sudo docker run -d --name redis -v redis-data:/data  \
-          -p 6379:6379  redis redis-server --appendonly yes
+          if [ "${{matrix.meta}}" == "fdb" ]; then
+            echo ::set-output name=target::"juicefs.fdb"
+          else
+            echo ::set-output name=target::"juicefs"
+          fi
+
+      - name: Build
+        uses: ./.github/actions/build
+        with: 
+          target: ${{steps.vars.outputs.target}}
+
+      - name: Prepare meta db
+        run: | 
+          chmod +x .github/scripts/start_meta_engine.sh
+          source .github/scripts/start_meta_engine.sh
+          start_meta_engine ${{matrix.meta}}
+          meta_url=$(get_meta_url ${{matrix.meta}})
+          create_database $meta_url
 
       - name: Juicefs Format
         run: |
-          sudo ./juicefs format redis://127.0.0.1:6379/1 --trash-days 0 pics
+          source .github/scripts/start_meta_engine.sh
+          meta_url=$(get_meta_url ${{matrix.meta}})
+          sudo ./juicefs format $meta_url --trash-days 0 pics
 
       - name: Juicefs Mount
         run: |
-          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /tmp/jfs --no-usage-report &
+          source .github/scripts/start_meta_engine.sh
+          meta_url=$(get_meta_url ${{matrix.meta}})
+          # sudo mkdir /var/jfs
+          # sudo chmod 777 /var/jfs
+          sudo ./juicefs mount -d $meta_url /tmp/jfs --no-usage-report &
+          sleep 5
+          if [ ! -f /tmp/jfs/.accesslog ]; then
+            echo "<FATAL>: mount failed"
+            exit 1
+          fi
 
       - name: Pjdfstest
         run: |
@@ -67,11 +120,18 @@ jobs:
           make pjdfstest
           sudo prove -rv tests/
 
-      - name: Log
+      - name: log
         if: ${{ always() }}
-        run: |
-          tail -n 1000 /var/log/juicefs.log
-          grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true
+        shell: bash
+        run: | 
+          if [ -f ~/.juicefs/juicefs.log ]; then
+            tail -300 ~/.juicefs/juicefs.log
+            grep "<FATAL>:" ~/.juicefs/juicefs.log && exit 1 || true
+          fi
+          if [ -f /var/log/juicefs.log ]; then
+            tail -300 /var/log/juicefs.log
+            grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true
+          fi
 
       - name: Send Slack Notification
         if: ${{ failure() }}
@@ -82,4 +142,5 @@ jobs:
 
       - name: Setup upterm session
         if: ${{ failure() }}
+        timeout-minutes: 1
         uses: lhotari/action-upterm@v1
