add multiclient test

diff --git a/.github/workflows/mdtest.yml b/.github/workflows/mdtest.yml
--- a/.github/workflows/mdtest.yml
+++ b/.github/workflows/mdtest.yml
@@ -1,32 +1,64 @@
 name: "mdtest"
 
 on:
+  push:
+    branches:
+      - 'main'
+      - 'release-**'
+    paths-ignore:
+      - 'docs/**'
+      - '**.md'
+  pull_request:
+    branches:
+      - 'main'
+      - 'release-**'
+    paths-ignore:
+      - 'docs/**'
+      - '**.md'
+      - '.github/**'
+  schedule:
+    - cron:  '0 16 * * *'
   workflow_dispatch:
     inputs:
-      dirs:
-        description: 'directory width for each depth'
-        required: true
-        default: 10
-      depth:
-        description: 'depth of directory'
-        required: true
-        default: 10
-      files:
-        description: 'number of files for each directory'
-        required: true
-        default: 10
-      threads:
-        description: 'number of threads'
-        required: true
-        default: 10
-      bytes:
-        description: 'bytes of each file'
-        required: true
-        default: 0
+      debug:
+        type: boolean
+        description: "Run the build with tmate debugging enabled"
+        required: false
+        default: false
+
 jobs:
-  mdtest:
-    runs-on: [self-hosted, daily-build, bench-02]
+  build-matrix:
+    runs-on: ubuntu-latest
     steps:
+      - id: set-matrix
+        run: |
+          echo "github.event_name is ${{github.event_name}}"
+          echo "GITHUB_REF_NAME is ${GITHUB_REF_NAME}"
+          if [ "${{github.event_name}}" == "schedule"  ]; then
+            echo '::set-output name=meta_matrix::["sqlite3", "redis", "mysql", "tikv", "tidb", "postgres", "badger", "mariadb", "fdb"]'
+          elif [ "${{github.event_name}}" == "pull_request"  ]; then
+            echo '::set-output name=meta_matrix::["redis"]'
+          elif [ "${{github.event_name}}" == "workflow_dispatch"  ]; then
+            echo '::set-output name=meta_matrix::["redis"]'
+          else
+            echo '::set-output name=meta_matrix::["redis"]'
+          fi
+    outputs:
+      meta_matrix: ${{ steps.set-matrix.outputs.meta_matrix }}
+
+  mdtest:
+    needs: build-matrix
+    strategy:
+      fail-fast: false
+      matrix:
+        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: shogo82148/actions-setup-perl@v1
+        with:
+          perl-version: '5.34'
+
       - name: Checkout
         uses: actions/checkout@v2
         with:
@@ -35,51 +67,59 @@ jobs:
       - name: Set Variable
         id: vars
         run: |
-          echo ::set-output name=META_URL::redis://mymaster,172.27.0.1,172.27.0.2,172.27.0.3:26379/7
-          echo ::set-output name=MOUNT_POINT::/tmp/mdtest
-          echo ::set-output name=BACKWARD_VERSIONS::1
-          echo ::set-output name=PYROSCOPE_URL::http://172.27.0.1:4040
+          if [ "${{matrix.meta}}" == "fdb" ]; then
+            echo ::set-output name=target::"juicefs.fdb"
+          else
+            echo ::set-output name=target::"juicefs"
+          fi
 
       - name: Build
         uses: ./.github/actions/build
+        with: 
+          target: ${{steps.vars.outputs.target}}
 
-      - name: Clean Before
+      - name: Prepare meta db
+        run: | 
+          chmod +x .github/scripts/start_meta_engine.sh
+          source .github/scripts/start_meta_engine.sh
+          start_meta_engine ${{matrix.meta}}
+          meta_url=$(get_meta_url ${{matrix.meta}})
+          create_database $meta_url
+
+      - name: Juicefs Format
         run: |
-          rm /var/jfsCache/ -rf
-          if [ -d ${{ steps.vars.outputs.MOUNT_POINT }} ]; then
-            ./juicefs umount ${{ steps.vars.outputs.MOUNT_POINT }} || true
-          fi
-          UUID=$(./juicefs status ${{ steps.vars.outputs.META_URL }} | grep UUID | cut -d '"' -f 4)
-          if [ -n "$UUID" ];then
-            sudo ./juicefs destroy --force ${{ steps.vars.outputs.META_URL }} $UUID
-          fi
+          source .github/scripts/start_meta_engine.sh
+          meta_url=$(get_meta_url ${{matrix.meta}})
+          sudo ./juicefs format $meta_url --trash-days 0 pics
 
-      - name: Fio Benchmark 
+      - name: Juicefs Mount
         run: |
-          export PYROSCOPE_AUTH_TOKEN="${{ secrets.PYROSCOPE_AUTH_TOKEN }}"  
-          meta_url=${{ steps.vars.outputs.META_URL }}
-          minio_url=http://172.27.0.2:9005/mdtest
-          dirs=${{ github.event.inputs.dirs }}
-          depth=${{ github.event.inputs.depth }}
-          files=${{ github.event.inputs.files }}
-          bytes=${{ github.event.inputs.bytes }}
-          threads=${{ github.event.inputs.threads }}
-
-          ./juicefs format --help | grep "trash-days" && trash_day="--trash-days 0" || trash_day=""
-          ./juicefs --help | grep "pyroscope" && pyroscope="--pyroscope ${{steps.vars.outputs.PYROSCOPE_URL}}" || pyroscope=""
-          ./juicefs format $trash_day --storage minio --bucket  $minio_url --access-key minioadmin --secret-key ${{ secrets.MINIO_SECRET_KEY }}  $meta_url mdtest
-          ./juicefs mount -d $meta_url ${{ steps.vars.outputs.MOUNT_POINT }} --no-usage-report $pyroscope 
-          ./juicefs mdtest $meta_url test --dirs $dirs --depth $depth --files $files --threads $threads --write $bytes
-
-      - name: Clean After
-        if: ${{always()}}
-        run: |
-          if [ -d ${{ steps.vars.outputs.MOUNT_POINT }} ]; then
-            ./juicefs umount ${{ steps.vars.outputs.MOUNT_POINT }} || true
+          source .github/scripts/start_meta_engine.sh
+          meta_url=$(get_meta_url ${{matrix.meta}})
+          # sudo mkdir /var/jfs
+          # sudo chmod 777 /var/jfs
+          sudo ./juicefs mount -d $meta_url /tmp/jfs --no-usage-report &
+          sleep 5
+          if [ ! -f /tmp/jfs/.accesslog ]; then
+            echo "<FATAL>: mount failed"
+            exit 1
           fi
-          UUID=$(./juicefs status ${{ steps.vars.outputs.META_URL }} | grep UUID | cut -d '"' -f 4)
-          if [ -n "$UUID" ];then
-            sudo ./juicefs destroy --force ${{ steps.vars.outputs.META_URL }} $UUID
+
+      - name: Pjdfstest
+        run: |
+          exit 0
+
+      - name: log
+        if: ${{ always() }}
+        shell: bash
+        run: | 
+          if [ -f ~/.juicefs/juicefs.log ]; then
+            tail -300 ~/.juicefs/juicefs.log
+            grep "<FATAL>:" ~/.juicefs/juicefs.log && exit 1 || true
+          fi
+          if [ -f /var/log/juicefs.log ]; then
+            tail -300 /var/log/juicefs.log
+            grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true
           fi
 
       - name: Send Slack Notification
@@ -88,3 +128,8 @@ jobs:
         with:
           channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
           slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  
+
+      - name: Setup upterm session
+        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug }}
+        timeout-minutes: 60
+        uses: lhotari/action-upterm@v1
